name: Cull Stale Issues
on:
  schedule:
    - cron: "30 1 * * *"
jobs:
  stale:
    steps:
      - uses: actions/stale@v4
        with:
          only-issue-labels: "needs-information"
          # -1 here means that PRs will never be marked as stale
          days-before-pr-stale: -1
